name: test_automation_demo
description: A minimal Flutter project showcasing unit, widget, golden, and integration tests.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true